// Auto-generated by the generator
// Don't manually edit this file

// @flow

import {getProjectList} from './getProjectList'
import {getProjectCards} from './getProjectCards'
import {getColumnCards} from './getColumnCards'
import {getProjectCardsByColumns} from './getProjectCardsByColumns'

export const systemSelectors = {
  getProjectList,
  getProjectCards,
  getColumnCards,
  getProjectCardsByColumns,
}
