// Auto-generated by the generator
// Don't manually edit this file

// @flow

import type {Action} from '../../types'
import type {SystemState} from '../types'

import {setCardsReducer} from './setCards'
import {setColumnsReducer} from './setColumns'
import {setProjectsReducer} from './setProjects'
import {setCardToProjectReducer} from './setCardToProject'
import {setProjectCardsReducer} from './setProjectCards'
import {initialState} from './initialState'

export const systemReducer = (state: SystemState = initialState, action: Action<any>): SystemState => {
  switch (action.type) {
    case 'system/SET_CARDS':
      return setCardsReducer(state, action)
    case 'system/SET_COLUMNS':
      return setColumnsReducer(state, action)
    case 'system/SET_PROJECTS':
      return setProjectsReducer(state, action)
    case 'system/SET_CARD_TO_PROJECT':
      return setCardToProjectReducer(state, action)
    case 'system/SET_PROJECT_CARDS':
      return setProjectCardsReducer(state, action)
    default:
      return state
  }
}
