// Auto-generated by the generator
// Don't manually edit this file

// @flow

import {setCards} from './setCards'
import {setColumns} from './setColumns'
import {setProjects} from './setProjects'
import {setCardToProject} from './setCardToProject'
import {setProjectCards} from './setProjectCards'

export const systemActions = {
  setCards,
  setColumns,
  setProjects,
  setCardToProject,
  setProjectCards,
}
