// Auto-generated by the generator
// Don't manually edit this file

// @flow

import type {SystemState} from './system/types'

export type Action<P> = {
  type: string,
  payload: P
}

export type Reducer<S, P> = (state: S, action: Action<P>) => S

export type Effect = Generator<any, any, any>

export type ApplicationState = {
  system: SystemState,
}
